// Handoffs — every account's latest handoff packet. Route: #/handoffs
// One row per account (latest status), in-flight handoffs sort first.
import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { fetchHandoffs, statusRank } from '../lib/handoffs';

// Lifecycle colours. Draft/Questions/Ready = still being worked; Shared =
// handed over, awaiting pickup; Accepted/Complete = settled.
const STATUS_STYLE = {
  'Draft':             { color: '#6b7280', bg: '#f3f4f6', border: '#e5e7eb' },
  'Questions Pending': { color: '#b45309', bg: '#fffbeb', border: '#fde68a' },
  'Ready':             { color: '#1d4ed8', bg: '#eff6ff', border: '#bfdbfe' },
  'Shared':            { color: '#059669', bg: '#ecfdf5', border: '#a7f3d0' },
  'Accepted':          { color: '#0f766e', bg: '#f0fdfa', border: '#99f6e4' },
  'Complete':          { color: '#374151', bg: '#f9fafb', border: '#e5e7eb' },
};
const UNKNOWN_STYLE = { color: '#6b7280', bg: '#f3f4f6', border: '#e5e7eb' };
const statusStyle = (status) => STATUS_STYLE[status] || UNKNOWN_STYLE;

const s = {
  wrap: { maxWidth: 1040, margin: '0 auto', padding: '40px 24px', fontFamily: "'DM Sans', sans-serif" },
  head: { display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 4 },
  title: { fontSize: 22, fontWeight: 700, color: '#1a1a1a' },
  sub: { fontSize: 14, color: '#6b7280', marginBottom: 24 },
  filters: { display: 'flex', gap: 8, marginBottom: 16, flexWrap: 'wrap' },
  chip: (active) => ({
    fontSize: 12, fontFamily: "'JetBrains Mono', monospace", padding: '4px 10px',
    borderRadius: 999, cursor: 'pointer', border: '1px solid',
    borderColor: active ? '#059669' : '#e2e5e9',
    color: active ? '#059669' : '#6b7280', background: active ? '#ecfdf5' : '#fff',
  }),
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 14 },
  th: {
    textAlign: 'left', padding: '8px 12px', fontSize: 10, fontWeight: 700,
    letterSpacing: '.12em', textTransform: 'uppercase', color: '#8a9099',
    fontFamily: "'JetBrains Mono', monospace", borderBottom: '1px solid #e2e5e9',
  },
  td: { padding: '12px', borderBottom: '1px solid #f0f1f3', color: '#1a1a1a', verticalAlign: 'top' },
  rowClickable: { cursor: 'pointer' },
  badge: (st) => ({
    display: 'inline-block', fontSize: 11, fontWeight: 700, letterSpacing: '.02em',
    color: st.color, background: st.bg, border: `1px solid ${st.border}`,
    borderRadius: 999, padding: '2px 10px', whiteSpace: 'nowrap',
  }),
  flag: {
    display: 'inline-block', fontSize: 11, fontWeight: 600, color: '#b45309',
    background: '#fffbeb', border: '1px solid #fde68a', borderRadius: 4,
    padding: '2px 8px', marginRight: 6, marginBottom: 2,
  },
  muted: { color: '#8a9099' },
  mono: { fontFamily: "'JetBrains Mono', monospace", fontSize: 12, color: '#6b7280' },
  note: { fontSize: 14, color: '#6b7280', padding: 24, textAlign: 'center' },
  error: { fontSize: 14, color: '#b91c1c', padding: 24, textAlign: 'center' },
};

const IN_FLIGHT = new Set(['Draft', 'Questions Pending', 'Ready', 'Shared']);

export default function Handoffs() {
  const navigate = useNavigate();
  const [handoffs, setHandoffs] = useState(null);
  const [error, setError] = useState('');
  const [filter, setFilter] = useState('all'); // 'all' | 'in-flight'

  useEffect(() => {
    let cancelled = false;
    fetchHandoffs()
      .then((h) => { if (!cancelled) setHandoffs(h); })
      .catch((e) => { if (!cancelled) setError(e?.message || String(e)); });
    return () => { cancelled = true; };
  }, []);

  const rows = useMemo(() => {
    if (!handoffs) return [];
    const filtered = filter === 'in-flight'
      ? handoffs.filter((h) => IN_FLIGHT.has(h.status))
      : handoffs;
    // In-flight first (lower statusRank), then most recently updated.
    return [...filtered].sort(
      (a, b) => statusRank(a.status) - statusRank(b.status)
        || (b.createdAt ?? '').localeCompare(a.createdAt ?? '')
    );
  }, [handoffs, filter]);

  if (error) {
    return (
      <div style={s.wrap}>
        <div style={s.error}>
          {/BQ 403/.test(error)
            ? 'You don’t have access to the call_prep dataset yet. Ask Nic for the BigQuery grant.'
            : `Couldn’t load handoffs: ${error}`}
        </div>
      </div>
    );
  }
  if (!handoffs) return <div style={s.wrap}><div style={s.note}>Loading handoffs…</div></div>;

  return (
    <div style={s.wrap}>
      <div style={s.head}>
        <h1 style={s.title}>Handoffs</h1>
        <span style={s.mono}>{handoffs.length} account{handoffs.length === 1 ? '' : 's'}</span>
      </div>
      <p style={s.sub}>Every account with a handoff packet, latest status first. Generated by the <code>/handoff</code> skill.</p>

      <div style={s.filters}>
        <span style={s.chip(filter === 'all')} onClick={() => setFilter('all')}>All</span>
        <span style={s.chip(filter === 'in-flight')} onClick={() => setFilter('in-flight')}>In flight</span>
      </div>

      {!rows.length && (
        <div style={s.note}>
          {handoffs.length ? 'No handoffs match this filter.' : 'No handoffs generated yet. Run /handoff [Account] to create one.'}
        </div>
      )}

      {rows.length > 0 && (
        <table style={s.table}>
          <thead>
            <tr>
              <th style={s.th}>Account</th>
              <th style={s.th}>Transition</th>
              <th style={s.th}>Status</th>
              <th style={s.th}>Open scope</th>
              <th style={s.th}>Catalogue</th>
              <th style={s.th}>Updated</th>
              <th style={s.th}>Flags</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((h) => (
              <tr
                key={h.accountRecordId}
                style={s.rowClickable}
                onClick={() => navigate(`/handoffs/account/${encodeURIComponent(h.accountRecordId)}`)}
              >
                <td style={{ ...s.td, fontWeight: 600 }}>{h.accountName ?? `#${h.accountRecordId}`}</td>
                <td style={s.td}>
                  <span>{h.outgoingRep ?? '—'}</span>
                  <span style={s.muted}> → </span>
                  <span>{h.incomingRep ?? <span style={s.muted}>TBD</span>}</span>
                </td>
                <td style={s.td}><span style={s.badge(statusStyle(h.status))}>{h.status ?? '—'}</span></td>
                <td style={s.td}>
                  {h.openInProgress} in progress · {h.openPromised} promised
                </td>
                <td style={s.td}>{h.catalogueMatches || '—'}</td>
                <td style={{ ...s.td, ...s.mono }}>{(h.createdAt ?? '').slice(0, 10) || '—'}</td>
                <td style={s.td}>
                  {h.flags.length
                    ? h.flags.map((f) => <span key={f} style={s.flag}>{f}</span>)
                    : <span style={s.muted}>—</span>}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
